Java 21 virtual thread support
quartz-scheduler/quartz pull request #1093
Opened 2023-12-19 06:16 UTC by nmondal

In submitting this contribution, I agree to the current Software AG contributor agreement as referred to here: 
https://github.com/quartz-scheduler/contributing/blob/main/CONTRIBUTING.md

This PR...
## Changes

Adds a `SimpleVirtualThreadPool` to do a virtual thread support.

## Checklist
- [ X]  tested locally
- [ ]   updated the docs
- [ X]  added appropriate test
- [ ]  signed-off on the above mentioned SoftwareAG contributor agreement via `git commit -s` on my commits. 
  (If you're not using command-line, you can use a [browser extension](https://github.com/scottrigby/dco-gh-ui) )

## Known Issues

In java 21 - the following tests fail:

```
> Task :quartz:test

org.quartz.impl.jdbcjobstore.StdJDBCDelegateTest > testSelectSimpleTriggerWithDeleteBeforeSelectExtendedProps FAILED
    java.lang.ExceptionInInitializerError at StdJDBCDelegateTest.java:119
        Caused by: java.lang.reflect.InaccessibleObjectException at StdJDBCDelegateTest.java:119

org.quartz.impl.jdbcjobstore.StdJDBCDelegateTest > testSelectSimpleTriggerWithExceptionWithExtendedProps FAILED
    java.lang.NoClassDefFoundError at StdJDBCDelegateTest.java:90
        Caused by: java.lang.ExceptionInInitializerError at StdJDBCDelegateTest.java:119

org.quartz.impl.jdbcjobstore.StdJDBCDelegateTest > testSelectBlobTriggerWithNoBlobContent FAILED
    java.lang.NoClassDefFoundError at StdJDBCDelegateTest.java:73
        Caused by: java.lang.ExceptionInInitializerError at StdJDBCDelegateTest.java:119

org.quartz.impl.jdbcjobstore.StdJDBCDelegateTest > testSelectTriggerToAcquireHonorsMaxCount FAILED
    java.lang.NoClassDefFoundError at StdJDBCDelegateTest.java:145
        Caused by: java.lang.ExceptionInInitializerError at StdJDBCDelegateTest.java:119

org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphoreTest > testSingleFailureFollowedBySuccessUsingUpdate FAILED
    java.lang.ExceptionInInitializerError at UpdateLockRowSemaphoreTest.java:35
        Caused by: java.lang.reflect.InaccessibleObjectException at UpdateLockRowSemaphoreTest.java:35

org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphoreTest > testDoubleFailureFollowedBySuccessUsingUpdate FAILED
    java.lang.NoClassDefFoundError at Unsafe.java:-2
        Caused by: java.lang.ExceptionInInitializerError at UpdateLockRowSemaphoreTest.java:35

org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphoreTest > testFallThroughToInsert FAILED
    java.lang.NoClassDefFoundError at Unsafe.java:-2
        Caused by: java.lang.ExceptionInInitializerError at UpdateLockRowSemaphoreTest.java:35

org.quartz.impl.jdbcjobstore.UpdateLockRowSemaphoreTest > testSingleSuccessUsingUpdate FAILED
    java.lang.NoClassDefFoundError at Unsafe.java:-2
        Caused by: java.lang.ExceptionInInitializerError at UpdateLockRowSemaphoreTest.java:35

319 tests completed, 8 failed, 1 skipped

> Task :quartz:test FAILED

FAILURE: Build failed with an exception.

```

2023-12-19 12:33 UTC, melloware approved these changes

2023-12-19 14:24 UTC, nmondal commented
@melloware  who would give us another approval?

2023-12-19 14:40 UTC, melloware commented
cc @jhouserizer 

I will admit it doesn't look like there has been much activity here which is dissapointing and last public release was 2019?

2023-12-19 14:45 UTC, jhouserizer commented
There were releases made earlier in the year (with dozens of changes) as RCs awaiting feedback.  Official non-RC releases will be made in the next week or two.

It's true that current efforts on the project are sporadic.  This contribution is interesting and will be looked at .

2023-12-20 05:44 UTC, nmondal commented
Added the DCO fix as expected by the doc.

2024-03-27 07:00 UTC, t-beckmann commented
There are no releases, no feedback on PRs nor on issues, no replies on the user's list, and the developer's forum link points to nowhere. Quartz is not only poorly maintained, but it is not maintained at all...

2024-04-03 23:30 UTC, raduking commented on quartz/src/main/java/org/quartz/simpl/SimpleVirtualThreadPool.java
> +/*
I think a code format should be run on these so that the formatting is consistent.

2024-08-30 01:09 UTC, t-beckmann requested changes

2024-08-30 01:09 UTC, t-beckmann commented on quartz/build.gradle
> +        println("External Java home '${JDK_PATH}' spefified for tests!")
These changes are not necessary, also typo here. Changes to build.gradle should be reverted.

2024-09-11 01:32 UTC, damingerdai commented on quartz/src/main/java/org/quartz/simpl/SimpleVirtualThreadPool.java
> +            log.warn( message + ex);
i think this is better
```java
  log.warn("{}{}", message, ex);
```

2024-10-11 16:40 UTC, closed without merging

2024-10-11 16:40 UTC, jhouserizer commented
Unfortunately, due to the change of ownership of this project, the terms of contribution have been updated, and this PR will need to be re-created, agreeing to the new terms.

2024-12-18 20:23 UTC, manofthepeace commented
@nmondal can this simply be re-created using the same branch you already have?

2024-12-29 19:02 UTC, nmondal commented
@manofthepeace  possible.